service: kid-min

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: python3.8

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function

package:
  individually: true
  exclude:
    - node_modules/**
    - local_*

functions:
  reminder:
    handler: handler.start
    module: reminder
    include:
      - reminder
    timeout: 10
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - s3:GetObject
          - s3:ListBucket
        Resource:
          - arn:aws:s3:::ladywood-kidmin
          - arn:aws:s3:::ladywood-kidmin/*
      - Effect: 'Allow'
        Action:
          - sns:Publish
        Resource:
          - "*"
    events:
      - schedule:
          arn: !GetAtt DailyRule.Arn
          rate: cron(05 00 * * ? *)
    
  
resources:
  Resources:  
    DailyRule:
      Type: AWS::Events::Rule
      Properties: 
        Description: "A daily trigger for the bday reminder function"
        Name: "DailyRule"
        ScheduleExpression: "cron(05 00 * * ? *)"
        State: "ENABLED"
        Targets: 
          - 
            Arn: 
              Fn::GetAtt: 
                - "ReminderLambdaFunction"
                - "Arn"
            Id: "ReminderLambdaFunction"
    
    PermissionForEventsToInvokeLambda: 
      Type: AWS::Lambda::Permission
      Properties: 
        FunctionName: !Ref ReminderLambdaFunction
        Action: "lambda:InvokeFunction"
        Principal: "events.amazonaws.com"
        SourceArn: 
          Fn::GetAtt: 
            - "DailyRule"
            - "Arn"